#! /usr/bin/env node

import inquirer from "inquirer";
import chalk from "chalk";

async function numberGuessingGame() {
    console.log(chalk.bold.cyanBright("Welcome to the Number Guessing Game!"));
    const {menu}= await inquirer.prompt([
        {
            name: "menu",
            type: "list",
            message: "Please select the given options:",
            choices: ["Play Game", "Instructions", "Exit"]
        }
    ]);
    async function playGameAgain() {
        if (menu=== "Play Game") {
            const randomNumber= Math.floor(Math.random()*10)+1;
            let attempts= 0;
            while (true) {
                const {playGame}= await inquirer.prompt([
                    {
                        name: "playGame",
                        type: "number",
                        message: "Guess a Number:",
                    }
                ]);
                attempts++;
                if (playGame=== randomNumber) {
                    console.log(chalk.bold.green(`Congratulations! You guessed the right number in ${attempts} attempts.`));
                    
                    const {playAgain}= await inquirer.prompt([
                        {
                            name: "playAgain",
                            type:"confirm",
                            message: "Do you want to play again?"
                        }
                    ]);
                    if (playAgain) {
                        console.log(chalk.bold.yellow("Welcome Again!"))
                        playGameAgain();
                    }
                    else{
                        console.log(chalk.bold.cyan("Thanks for Playing"))
                    }
                    break;
                }
                else{
                    console.log(chalk.bold.red("You guessed wrong number! Try again."))
                }
                
                
            }
        }
        else if (menu=== "Instructions") {
                console.log(chalk.bold.dim(`
     1:Computer will generate a random number and your task is to guess that number
     2:The limit of number to guess is between (1-10)
     3:If you will guess the number randomly generated by computer then it will convey you a message that you guessed right number
     4:If you guess a wrong number then it will convey you a message of try again
     `));
     const {addMoreOptions}= await inquirer.prompt([
        {
            name: "addMoreOptions",
            message:"Please Select given Options:",
            type: "list",
            choices:["Main Menu", "Exit"]
        }
     ]);
     if (addMoreOptions=== "Main Menu") {
        numberGuessingGame();
     }
        }
        
    }
    playGameAgain();
    
}
numberGuessingGame();
 

